/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class programs_studyprogram_core_businessdeal_JniBusi */
//生成cpp头文件命令代码格式：
//D:\Jiang\androidProjects\ModulesProject\moduledemo\src\main>
// javah -d cpp -classpath D:\sdk\platforms\android-N\android.jar;
// ..\..\build\intermediates\classes\debug modulesproject.moduledemo.hierarchical.business.busideals.TestJni
//

#ifndef _Included_programs_studyprogram_core_businessdeal_JniBusi
#define _Included_programs_studyprogram_core_businessdeal_JniBusi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     programs_studyprogram_core_businessdeal_JniBusi
 * Method:    versionCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_programs_studyprogram_core_businessdeal_JniBusi_versionCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
